In [94]:
import xgboost as xgb
import numpy as np
import pandas as pd

# Load data

In [95]:
X_train = pd.read_csv('data/X_train.csv')
X_test = pd.read_csv('data/X_test.csv')
y_train = np.loadtxt('data/y_train.csv', delimiter=',')
y_test = np.loadtxt('data/y_test.csv', delimiter=',')

test = pd.read_csv('data/test.csv')

In [96]:
X_train.drop(X_train.columns[0], axis=1, inplace=True)
X_test.drop(X_test.columns[0], axis=1, inplace=True)

In [97]:
X_train

,f0,f1,f2,f3,f5,f6,f7,f9,f10,f11,...,f21_bbx,f21_bd,f21_bx,f21_dbd,f21_n,f21_nd,f21_nnd,f21_nx,f21_x,f21_xbx
0,21.4,22.0,16.4,25.3,13.000000,65.0,22.0,0.0,9.400000,28.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,12.8,35.0,7.8,18.4,9.700000,41.0,17.0,0.0,6.200000,22.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,24.3,43.0,19.3,16.1,10.800000,33.0,19.0,0.0,4.600000,23.5,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,13.9,29.0,8.9,16.8,7.780425,70.0,19.0,0.0,7.573920,23.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,26.1,27.0,21.1,14.1,6.900000,28.0,13.0,0.0,4.000000,20.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42231,23.5,7.0,18.5,20.1,11.900000,28.0,15.0,0.0,5.200000,21.7,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
42232,24.8,33.0,19.8,16.8,10.966297,24.0,6.0,0.0,5.461769,27.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42233,22.8,34.0,17.8,8.7,3.800000,48.0,19.0,0.0,1.200000,14.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42234,13.9,15.0,8.9,20.9,11.900000,31.0,11.0,0.0,10.000000,32.1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
42235,22.9,15.0,17.9,21.9,0.000000,39.0,11.0,0.0,8.000000,21.9,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Load model

In [98]:
model = xgb.XGBClassifier()
model.load_model('best_model.json')

In [99]:
from sklearn import metrics

def auc(m, test, y_test): 
    return metrics.roc_auc_score(y_test, m.predict_proba(test)[:,1])

In [100]:
y_train.shape

(42236,)

In [101]:
X_train.shape

(42236, 49)

## Estimate performance

In [102]:
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1.0, gamma=1e-09, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.05, max_delta_step=0, max_depth=50,
              min_child_weight=6, missing=nan, monotone_constraints='()',
              n_estimators=500, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1.0,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [103]:
auc(model, X_test, y_test)

0.9325339344547737

# Make predictions on test data

In [104]:
test.drop(test.columns[0], axis=1, inplace=True)

In [105]:
predictions = model.predict_proba(test)
ids = [i for i in range(50000,100000,1)]
id_preds = pd.DataFrame({'sample_id': ids, 'prediction_in_probability': predictions[:,1]})
id_preds.head(20)

    sample_id  prediction_in_probability
0       50000                   0.160751
1       50001                   0.000741
2       50002                   0.000512
3       50003                   0.962810
4       50004                   0.000544
5       50005                   0.070813
6       50006                   0.000344
7       50007                   0.088326
8       50008                   0.000257
9       50009                   0.903031
10      50010                   0.000661
11      50011                   0.002570
12      50012                   0.001054
13      50013                   0.011956
14      50014                   0.025697
15      50015                   0.173255
16      50016                   0.008320
17      50017                   0.000113
18      50018                   0.003442
19      50019                   0.032418